CREATE TABLE IF NOT EXISTS tracks (
    id VARCHAR(255) PRIMARY KEY,
    name TEXT,
    popularity INTEGER,
    duration_ms INTEGER,
    explicit BOOLEAN,
    artists TEXT[],
    id_artists TEXT[],
    danceability VARCHAR(10),
    energy FLOAT,
    keyf INTEGER,
    loudness FLOAT,
    modef INTEGER,
    speechiness FLOAT,
    acousticness FLOAT,
    instrumentalness FLOAT,
    liveness FLOAT,
    valence FLOAT,
    tempo FLOAT,
    time_signature INTEGER,
    year INTEGER,
    month INTEGER,
    day INTEGER
);